name: "cloudflared-stack"
services:
  cloudflared:
    command:
    - tunnel
    - --no-autoupdate
    - run
    - --token
    - $CLOUDFLARED_TOKEN
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    networks:
      cloudflared-network: null
networks:
  cloudflared-network:
    name: cloudflared-network
    external: true